"""empty message

Revision ID: 3a8bdaf500b4
Revises: c13319eca706
Create Date: 2021-05-09 02:58:37.056345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8bdaf500b4'
down_revision = 'c13319eca706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('main_view', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('folder', 'main_view')
    # ### end Alembic commands ###
