"""empty message

Revision ID: 6183f888c85e
Revises: 85795faa8ca6
Create Date: 2021-02-06 20:47:12.319224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6183f888c85e'
down_revision = '85795faa8ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'priority')
    # ### end Alembic commands ###
