"""empty message

Revision ID: 670fba9cdd87
Revises: 6183f888c85e
Create Date: 2021-02-06 20:49:34.980098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '670fba9cdd87'
down_revision = '6183f888c85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
