"""empty message

Revision ID: 778c226aa6d6
Revises: 5eb39a939e44
Create Date: 2021-03-04 16:20:10.190257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778c226aa6d6'
down_revision = '5eb39a939e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'notes',
               existing_type=sa.VARCHAR(length=100000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'notes',
               existing_type=sa.VARCHAR(length=100000),
               nullable=False)
    # ### end Alembic commands ###
