"""empty message

Revision ID: 7d59eefddc30
Revises: 17d3c7152db5
Create Date: 2021-05-08 20:13:28.354895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d59eefddc30'
down_revision = '17d3c7152db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('toggle', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('side_bar', sa.Boolean(), nullable=True))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'side_bar')
    op.drop_column('folder', 'toggle')
    # ### end Alembic commands ###
