"""empty message

Revision ID: c13319eca706
Revises: 7d59eefddc30
Create Date: 2021-05-08 21:18:04.614330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13319eca706'
down_revision = '7d59eefddc30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('collapse', sa.Boolean(), nullable=True))
    op.drop_column('folder', 'toggle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folder', sa.Column('toggle', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('folder', 'collapse')
    # ### end Alembic commands ###
