"""empty message

Revision ID: ff78e420e382
Revises: 62fb0eac539b
Create Date: 2021-03-05 20:20:39.877081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff78e420e382'
down_revision = '62fb0eac539b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('notes_user_id_fkey', 'notes', type_='foreignkey')
    op.drop_column('notes', 'user_id')
    op.drop_constraint('task_user_id_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'user_id')
    op.add_column('user', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['last_name'])
    op.create_unique_constraint(None, 'user', ['first_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.add_column('task', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('task_user_id_fkey', 'task', 'user', ['user_id'], ['id'])
    op.add_column('notes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('notes_user_id_fkey', 'notes', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
